### ISSUE TITLE
I'm trying to set this up by myself, could you give me some pointers to finish it up?

### ISSUE THREAD

**Issue by mlunoe** [greenkeeperio/greenkeeper-shrinkwrap#1]
Hi there,

I am considering using this for one of my open source projects and I wanted to see if I could set this up.
Could you give me some pointers too what is missing, so I can help finish the project?
Is there a feature list or set of missing and required functionality for this to work?

Thanks,
Michael

**Comment by boennemann** [comment]
Hey @mlunoe,

thanks for offering your help here. I think you saw how we want this to work in the README.md.

There are some edge cases left to solve. 
- [x] For this to work the shrinkwrap file **must** be regenerated on every Greenkeeper (and only Greenkeeper) build.
- [ ] The upload has to happen whenever a branch build fails (inside range), or whenever a PR is opened directly (outside of the range).

The second part isn't yet solved. Ideally we would want to have a CI agnostic solution, that's still easy to setup. I think we'd need to split up our commands for this no matter what: update, upload.
I also think it would be necessary to move the upload script to an `after_script` hook to have the necessary information available.
There we need to figure out how detect failures/direct updates and then make sure we're not running into infinite loops, or race conditions while pushing code back to our branches.

It's not unsolvable, it's just a bit delayed on our roadmap.
If you want to give it a try we're more than happy to accept a contribution to this.

Best,
Stephan

**Comment by boennemann** [comment]
Oh and I almost forgot, e.g. Travis doesn't really checkout branches, but commit hashes in detached HEAD mode. Because of this we can't use [our current approach to extract the branch name](https://github.com/greenkeeperio/greenkeeper-shrinkwrap/blob/master/lib/extract-dependency.js#L7). Travis exposes the current branch name via an environment variable, but that wouldn't be a CI agnostic approach.

We could use git author information to detect Greenkeeper branches, and then parse information from the diff or the commit message for example.

**Comment by boennemann** [comment]
This is now published on npm and it works, but on Travis CI only (#5)

**Comment by mlunoe** [comment]
❤️
